#!/usr/bin/env node
// Usage: node build_snapshot.js <export.json> [outFile]
// Validates a Paper Notes export (the JSON from the app's "데이터 내보내기"
// button) and (re)writes notes-snapshot.js with the full state. Run from the
// repo root. Prints a JSON summary (counts, exportedAt) to stdout.

const fs = require("fs");
const path = require("path");

const inPath = process.argv[2];
const outFile = process.argv[3] || path.join(process.cwd(), "notes-snapshot.js");
if (!inPath) {
  console.error("usage: node build_snapshot.js <export.json> [outFile]");
  process.exit(2);
}

let data;
try {
  data = JSON.parse(fs.readFileSync(inPath, "utf8"));
} catch (e) {
  console.error("export JSON 읽기/파싱 실패: " + e.message);
  process.exit(1);
}

// Accept either the wrapped form {version, exportedAt, papers:[...]} or a bare array.
const papers = Array.isArray(data) ? data : data.papers;
if (!Array.isArray(papers)) {
  console.error("export 형식이 올바르지 않습니다: papers 배열을 찾을 수 없음.");
  process.exit(1);
}
const bad = papers.filter((p) => !p || !p.id || !p.title);
if (bad.length) {
  console.error(`항목 ${bad.length}개에 id/title이 없습니다. 올바른 Paper Notes export가 아닙니다.`);
  process.exit(1);
}

const snapshot = {
  version: (Array.isArray(data) ? 1 : data.version) || 1,
  exportedAt: (Array.isArray(data) ? null : data.exportedAt) || new Date().toISOString(),
  papers,
};

const banner =
  "// Full state snapshot of the Paper Notes app.\n" +
  "// Auto-generated by the `sync_to_repo` skill from the app's \"데이터 내보내기\" export.\n" +
  "// When `papers` is non-empty, app.js uses this as the source of truth for a fresh\n" +
  "// load (lossless: keeps note, status, collection, tags, abstract, favorite, etc.),\n" +
  "// superseding the curated seed files. Until the first sync it stays empty and the\n" +
  "// app falls back to catalog.js / paper-notes-data.js / study-notes-data.js.\n";

fs.writeFileSync(outFile, banner + "const notesSnapshot = " + JSON.stringify(snapshot, null, 2) + ";\n");

const types = papers.reduce((acc, p) => ((acc[p.type || "paper"] = (acc[p.type || "paper"] || 0) + 1), acc), {});
console.log(
  JSON.stringify(
    { outFile, total: papers.length, byType: types, exportedAt: snapshot.exportedAt },
    null,
    2
  )
);
